openapi: 3.0.0
info:
  title: SpazzaTN API
  version: 1.0.0
paths:
  /:
    get:
      summary: Retrieve a list of users
      description: >-
        Retrieve a list of users. If an email is provided as a query parameter,
        retrieve the user with that email.
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: false
          description: The email of the user to retrieve.
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    self:
                      type: string
                      description: The URL of the user.
                    email:
                      type: string
                      description: The email of the user.
  /register:
    post:
      summary: Register a new user
      description: 'Register a new user by providing an email, password, and username.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                  description: The user's email.
                password:
                  type: string
                  description: The user's password.
                username:
                  type: string
                  description: The user's username.
      responses:
        '201':
          description: User registered successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message.
        '400':
          description: 'The field "email" must be a non-empty string, in email format.'
        '409':
          description: The email is already in use.
        '500':
          description: Error saving user.
components: {}
tags: []
